import html
import re

def html_builder(title: str, text: str):
    page = f"<b>🎬 {html.escape(title)}</b><br><br>"

    current_section = None
    buffer = []

    def flush():
        nonlocal page, buffer

        if buffer:
            page += "<pre>"
            page += "\n".join(buffer)
            page += "</pre><br>"
            buffer.clear()

    for line in text.splitlines():
        line = html.escape(line.rstrip())

        if not line:
            continue

        if line == "General":
            flush()
            page += "<b>📄 General</b><br>"
            continue

        if line == "Video":
            flush()
            page += "<b>🎥 Video</b><br>"
            continue

        if line.startswith("Audio"):
            flush()
            page += f"<b>🔊 {line}</b><br>"
            continue

        if re.match(r"Text\s+#\d+", line):
            flush()
            page += f"<b>💬 {line}</b><br>"
            continue

        if line == "Menu":
            flush()
            page += "<b>📚 Chapters</b><br>"
            continue

        buffer.append(line)

    flush()

    page += "<br><b>Generated by MediaInfo Bot</b>"

    return page

from telegraph import Telegraph

telegraph = Telegraph()
telegraph.create_account(short_name="MediaInfoBot")

def mediainfo_paste(text: str, title: str):
    html_content = html_builder(title, text)

    response = telegraph.create_page(
        title=title[:256],
        html_content=html_content
    )

    return "https://telegra.ph/" + response["path"]
