css = """
<style>
@font-face {
font-family: 'JetBrainsMono';
src: url('https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono/web/woff2/JetBrainsMono-Regular.woff2') format('woff2'),
url('https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono/web/woff/JetBrainsMono-Regular.woff') format('woff'),
url('https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono/ttf/JetBrainsMono-Regular.ttf') format('truetype');
font-weight: 400;
font-style: normal;
}

.loader-pulse {
  position: relative;
  bottom: 0.17rem;
  width: 25px;
  height: 25px;
  float: left;
  border-radius: 50%;
  background: #50fa7b;
  animation: load-pulse 1s infinite linear;
}

@keyframes load-pulse {
  0% {
    transform: scale(0.05);
    opacity: 0;
  }

  50% {
    opacity: 1;
  }

  100% {
    transform: scale(0.5);
    opacity: 0;
  }
}

::-webkit-scrollbar {
    width: 3px;
    height: 3px;
}

::-webkit-scrollbar-corner ,
::-webkit-scrollbar-track {
    display: none;
}

::-webkit-scrollbar-thumb {
    border-radius: 8px;
    background-color: #50fa7b;
}

body {
background-color: #282a36;
font-family:  "Josefin Sans", sans-serif;
color: #f8f8f2;
overscroll-behaviour: contain;
}


code {
font-family: "Ubuntu mono", "Courier prime";
}

.container {
display: flex;
flex-direction: column;
}

.container.heading {
display: block;
text-align: center;
line-height: 20px;
flex-direction: column;

margin: auto;
margin-bottom: 50px;
padding: 20px 20px 20px 20px;
font-size: 1rem;
overflow: scroll;
background-color: rgba(255, 255, 255, 0.1);
border-radius: 7px;
border-style: dashed;
font-family: "Ubuntu mono", "Courier prime";
border: 2px solid rgba(255, 255, 255, 0.1);
}

.container.heading::-webkit-scrollbar {
display: none;
}

.container.subheading {
margin-left: 15px;
margin-bottom:15px;
padding-top: 10px; 
font-size: 1.4rem;
}

.container.infobox {
margin-bottom: 40px;
margin-left: 12px;
margin-right: 12px;
  
border-radius: 10px;
background:  rgba(255, 255, 255, 0.1);        
border: 2.5px solid rgba(255, 255, 255, 0.1);
padding: 10px 15px 15px 10px;
white-space: pre ;
overflow: scroll;
font-size: 0.9rem;
}

.subtitle {
display: grid;
grid-auto-flow: column;
grid-auto-columns:320px;
overflow-x: auto;
overscroll-behaviour-inline: contain;
margin-bottom: 40px;
margin-left: 7px;
margin-top: 12px;
}

.subtitle::-webkit-scrollbar {
display: none;
}

.container.subtitlebox {
margin-left: 5px;
margin-right: 15px;
margin-bottom: 0px;
border-radius: 10px; 
background: rgba(255, 255, 255, 0.1);          
border: 3px solid rgba(255, 255, 255, 0.1);
padding: 15px 15px 15px 10px;
white-space: nowrap;
overflow: scroll;
font-size: 0.9rem;
}

.icons {
float: left;
margin-left: 15px;
margin-right: 5px;
}

.footer {
position: fixed;
bottom: 0;
right: 0;
left: 0;
height: 32px;
width: 100%;
font-family: JetBrainsMono;
background-color: #212121;
}

.footer-text{
display: block;
justify-content: space-between;
font-size: 0.9rem;
padding-left: 0.7rem;
padding-right: 1.5rem;
padding-top: 0.25rem;
}
</style>
</head>
"""

import requests
import json
import re


import html
import re

def html_builder(title: str, text: str):
    page = f"<h2>🎬 {html.escape(title)}</h2>"

    current = None
    content = []

    def flush():
        nonlocal page, content, current
        if current:
            page += f"<h3>{current}</h3>"
            page += "<pre>"
            page += "\n".join(content)
            page += "</pre>"
        content = []

    icons = {
        "General": "📄 General",
        "Video": "🎥 Video",
        "Audio": "🔊 Audio",
        "Menu": "📚 Chapters",
    }

    for line in text.splitlines():
        line = html.escape(line.rstrip())

        if not line:
            continue

        if line.startswith("General"):
            flush()
            current = icons["General"]
            continue

        elif line.startswith("Video"):
            flush()
            current = icons["Video"]
            continue

        elif line.startswith("Audio"):
            flush()
            current = icons["Audio"]
            continue

        elif line.startswith("Menu"):
            flush()
            current = icons["Menu"]
            continue

        elif re.match(r"Text\s+#\d+", line):
            flush()
            current = f"💬 {line}"
            continue

        content.append(line)

    flush()

    page += (
        "<hr>"
        "<p><b>Generated by MediaInfo Bot</b></p>"
    )

    return page
  
from telegraph import Telegraph

telegraph = Telegraph()
telegraph.create_account(short_name="MediaInfoBot")

def mediainfo_paste(text: str, title: str):
    html_content = html_builder(title, text)

    response = telegraph.create_page(
        title=title[:256],
        html_content=html_content
    )

    return "https://telegra.ph/" + response["path"]
