import html
import re
from telegraph import Telegraph

def html_builder(title: str, text: str):
    page = f"<h2>🎬 {html.escape(title)}</h2>"

    current = None
    content = []

    def flush():
        nonlocal page, content, current
        if current:
            page += f"<h3>{current}</h3>"
            page += "<pre>"
            page += "\n".join(content)
            page += "</pre>"
        content = []

    icons = {
        "General": "📄 General",
        "Video": "🎥 Video",
        "Audio": "🔊 Audio",
        "Menu": "📚 Chapters",
    }

    for line in text.splitlines():
        line = html.escape(line.rstrip())

        if not line:
            continue

        if line.startswith("General"):
            flush()
            current = icons["General"]
            continue

        elif line.startswith("Video"):
            flush()
            current = icons["Video"]
            continue

        elif line.startswith("Audio"):
            flush()
            current = icons["Audio"]
            continue

        elif line.startswith("Menu"):
            flush()
            current = icons["Menu"]
            continue

        elif re.match(r"Text\s+#\d+", line):
            flush()
            current = f"💬 {line}"
            continue

        content.append(line)

    flush()

    page += (
        "<hr>"
        "<p><b>Generated by MediaInfo Bot</b></p>"
    )

    return page
  


telegraph = Telegraph()
telegraph.create_account(short_name="MediaInfoBot")

def mediainfo_paste(text: str, title: str):
    html_content = html_builder(title, text)

    response = telegraph.create_page(
        title=title[:256],
        html_content=html_content
    )

    return "https://telegra.ph/" + response["path"]
